# Generated by Django 5.1 on 2024-08-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barCode', models.CharField(max_length=100)),
                ('assetName', models.CharField(max_length=100)),
                ('location', models.TextField()),
            ],
        ),
    ]
