# Generated by Django 5.1 on 2024-08-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_location_alter_barcode_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
