# Generated by Django 5.1 on 2024-08-20 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_barcode_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.location'),
        ),
    ]
