# Generated by Django 5.1 on 2024-08-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_location_level_location_parent_alter_location_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='level',
            field=models.CharField(choices=[('country', 'Country'), ('governate', 'Governate'), ('area', 'Area'), ('building', 'Building'), ('office', 'Office')], default='country', max_length=20),
        ),
    ]
