# Generated by Django 5.1 on 2024-08-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_location_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='sequenceEnd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='sequenceStart',
            field=models.IntegerField(default=0),
        ),
    ]
