# Generated by Django 5.1 on 2024-08-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_asset_sequenceend_asset_sequencestart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='name',
            new_name='assetTag',
        ),
    ]
