# Generated by Django 5.1 on 2024-08-21 09:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_name_asset_assettag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='sequenceEnd',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='sequenceStart',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='asset',
        ),
        migrations.AddField(
            model_name='asset',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='myapp.inventory'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='startDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
