# Generated by Django 5.1 on 2024-08-22 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_area_country_alter_asset_inventory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='level',
        ),
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='parent',
        ),
        migrations.AddField(
            model_name='location',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='myapp.area'),
        ),
        migrations.AddField(
            model_name='location',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='myapp.building'),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='myapp.country'),
        ),
        migrations.AddField(
            model_name='location',
            name='governate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='myapp.governate'),
        ),
        migrations.AddField(
            model_name='location',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='myapp.office'),
        ),
        migrations.AlterField(
            model_name='area',
            name='governate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas', to='myapp.governate'),
        ),
        migrations.AlterField(
            model_name='building',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', to='myapp.area'),
        ),
        migrations.AlterField(
            model_name='governate',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governates', to='myapp.country'),
        ),
        migrations.AlterField(
            model_name='office',
            name='Building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offices', to='myapp.building'),
        ),
    ]
