# Generated by Django 5.1 on 2024-08-22 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_asset_id_alter_asset_inventory_assetcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='myapp.assetcount'),
        ),
        migrations.RemoveField(
            model_name='assetcount',
            name='asset',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
