# Generated by Django 5.1 on 2024-08-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_asset_inventory_remove_assetcount_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcount',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
