# Generated by Django 5.1 on 2024-08-22 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_assetcount_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='inventory',
            new_name='assetCount',
        ),
    ]
