# Generated by Django 5.1 on 2024-08-22 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_rename_inventory_asset_assetcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assetCount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='myapp.assetcount'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetTag',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('assetTag', 'assetCount')},
        ),
    ]
