# Generated by Django 5.1 on 2024-08-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_asset_assetcount_alter_asset_assettag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assetTag',
            field=models.CharField(max_length=255),
        ),
    ]
