# Generated by Django 5.1 on 2024-08-22 10:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_asset_assettag'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
