# Generated by Django 5.1 on 2024-08-22 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_area_created_on_area_updated_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetcount',
            name='office',
        ),
        migrations.AlterField(
            model_name='assetcount',
            name='startDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
