# Generated by Django 5.1 on 2024-08-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_category_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
