# Generated by Django 5.1 on 2024-08-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_barcode_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcode',
            name='pdf_file',
        ),
    ]
