# Generated by Django 5.1 on 2024-08-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_remove_barcode_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_num', models.IntegerField(default=0)),
                ('end_num', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='barcode',
            name='end_num',
        ),
        migrations.RemoveField(
            model_name='barcode',
            name='start_num',
        ),
    ]
