# Generated by Django 5.1 on 2024-08-27 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_configuration_remove_barcode_end_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='configuration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.configuration'),
            preserve_default=False,
        ),
    ]
