# Generated by Django 5.1 on 2024-08-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_barcode_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcode',
            name='configuration',
        ),
    ]
