# Generated by Django 5.1 on 2024-08-27 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_barcode_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.barcode')),
            ],
        ),
    ]
