# Generated by Django 5.1 on 2024-08-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_alter_images_barcode_alter_images_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
