# Generated by Django 5.1 on 2024-08-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_configuration_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='used',
        ),
    ]
