# Generated by Django 5.1 on 2024-08-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_remove_configuration_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='end_num',
            field=models.IntegerField(default=1),
        ),
    ]
