# Generated by Django 5.1 on 2024-08-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_alter_configuration_end_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcode',
            name='configuration',
        ),
    ]
